// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EqCatalogAPI.Models;

public partial class EquipmentStatus
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [StringLength(30)]
    public string Status { get; set; }

    [InverseProperty("Status")]
    public virtual ICollection<Equipment> Equipment { get; set; } = new List<Equipment>();
}